config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'hello_world/index', to: 'hello_world#index'
  post '/users/create', to: 'users#create'
  post '/users/delete', to: 'users#destroy'
  post '/users/edit', to: 'users#update'
  post '/users/login', to: 'users#login'
  post '/users/logout', to: 'users#logout'
  post '/todo_lists/get', to: 'todo_lists#index'
  post '/todo_lists/create', to: 'todo_lists#create'
  delete '/todo_lists/delete', to: 'todo_lists#destroy'
  patch '/todo_lists/update', to: 'todo_lists#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :todo_lists
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]

  # post 'password_resets', to: 'password_resets#create'
  # get 'password_resets/new', to: 'password_resets#new'
end

app/controllers/password_resets_controller.rb
# frozen_string_literal: true

class PasswordResetsController < ActionController::Base
  include UserHelper

  before_action :get_user,         only: %i[edit update]
  before_action :valid_user,       only: %i[edit update]
  before_action :check_expiration, only: %i[edit update]

  def new; end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = '登録されているメールアドレス宛にメールを送りました'
    else
      flash.now[:danger] = 'そのようなメールアドレスは登録されていません'
    end
    render :new
  end

  def edit; end

  def update
    if params[:user][:password].empty? || params[:user][:password] != params[:user][:password_confirmation]
      return render :edit
    end

    @user.password = user_params[:password]

    @user.password_digest = User.digest(@user.password)
    if @user.save
      redirect_to 'https://takashiii-hq.com'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password)
  end

  def get_user
    @user = User.find_by(email: params[:email])
  end

  # 有効なユーザーかどうか確認する
  def valid_user
    unless @user&.activated? &&
           @user&.authenticated?(:reset, params[:id])
      redirect_to 'https://takashiii-hq.com'
    end
  end

  # トークンが期限切れかどうか確認する
  def check_expiration
    return unless @user.password_reset_expired?

    flash[:danger] = 'Password reset has expired.'
    redirect_to new_password_reset_url
  end
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <% flash.each do |message_type, message| %>
    <div class=<%=message_type%>><%= message %></div>
  <% end %>
    <%= form_with(model: @user, url: password_reset_path(params[:id], protocol: 'https'),
                  local: true) do |f| %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <% flash.each do |message_type, message| %>
    <div class=<%=message_type%>><%= message %></div>
  <% end %>
    <%= form_with(url: password_resets_path(protocol: 'https'), scope: :password_reset,
                    local: true) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>